export enum Events {
  NONE,
  OPEN_INVITE_USER_POPUP,
  CLOSE_INVITE_USER_POPUP,
  OPEN_REMOVE_USER_CONFIRM_POPUP,
  CLOSE_REMOVE_USER_CONFIRM_POPUP,
  ADD_USER,
  REMOVE_USER,
  REMOVE_USER_PAYLOAD,
  FILTER_USERS
}
